package today.vanta.util.client.music;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.URI;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Base64;
import java.util.Locale;

// generated by our beloved AI, Claude!
public final class MediaGrabber {
    private static final long POLL_INTERVAL_MS = 1000L;

    private static volatile String artist = "";
    private static volatile String title = "";
    private static volatile long millisLength = 0L;
    private static volatile long millisPosition = 0L;
    private static volatile byte[] coverBytes = null;

    private static String lastArtKey = "";
    private static volatile boolean running = false;
    private static boolean loggedFailure = false;

    private static final Backend BACKEND = detectBackend();


    public static synchronized void start() {
        if (running) {
            return;
        }
        running = true;
        Thread pollThread = new Thread(MediaGrabber::pollLoop, "MediaPlayerInfo-Poller");
        pollThread.setDaemon(true);
        pollThread.start();
    }

    public static synchronized void stop() {
        running = false;
    }

    private static Backend detectBackend() {
        String os = System.getProperty("os.name", "").toLowerCase(Locale.ROOT);
        if (os.contains("win")) {
            return new WindowsBackend();
        } else if (os.contains("mac") || os.contains("darwin")) {
            return new MacBackend();
        } else {
            return new LinuxBackend();
        }
    }

    private static void pollLoop() {
        while (running) {
            try {
                Snapshot snapshot = BACKEND.poll();
                applySnapshot(snapshot);
            } catch (Exception e) {
                if (!loggedFailure) {
                    System.err.println("[MediaPlayerInfo] Couldn't read media info via "
                            + BACKEND.getClass().getSimpleName() + " (is the required tool installed and on PATH? "
                            + "see class docs for what's needed on " + System.getProperty("os.name") + "): "
                            + e.getMessage());
                    loggedFailure = true;
                }
            }
            try {
                Thread.sleep(POLL_INTERVAL_MS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
        }
    }

    private static void applySnapshot(Snapshot snapshot) {
        if (snapshot == null || !snapshot.hasMedia) {
            artist = "";
            title = "";
            millisLength = 0L;
            millisPosition = 0L;
            coverBytes = null;
            lastArtKey = "";
            return;
        }

        artist = snapshot.artist;
        title = snapshot.title;
        millisLength = snapshot.millisLength;
        millisPosition = snapshot.millisPosition;

        String artKey = snapshot.artKey();
        if (!artKey.equals(lastArtKey)) {
            lastArtKey = artKey;
            coverBytes = snapshot.resolveCoverBytes();
        }
    }

    public static String getArtist() {
        return artist;
    }

    public static String getTitle() {
        return title;
    }

    public static long getMillisLength() {
        return millisLength;
    }

    public static long getMillisPosition() {
        return millisPosition;
    }

    public static byte[] getCoverBytes() {
        return coverBytes;
    }

    public static BufferedImage getCoverImage() {
        byte[] bytes = coverBytes;
        if (bytes == null) {
            return null;
        }
        try {
            return ImageIO.read(new ByteArrayInputStream(bytes));
        } catch (IOException e) {
            return null;
        }
    }

    private static final class Snapshot {
        final boolean hasMedia;
        final String artist;
        final String title;
        final long millisLength;
        final long millisPosition;

        final String coverRef;
        final CoverKind coverKind;

        static final Snapshot EMPTY = new Snapshot(false, "", "", 0, 0, null, CoverKind.NONE);

        Snapshot(boolean hasMedia, String artist, String title, long millisLength, long millisPosition,
                 String coverRef, CoverKind coverKind) {
            this.hasMedia = hasMedia;
            this.artist = artist;
            this.title = title;
            this.millisLength = millisLength;
            this.millisPosition = millisPosition;
            this.coverRef = coverRef;
            this.coverKind = coverKind;
        }

        String artKey() {
            if (coverKind == CoverKind.BASE64) {
                String ref = coverRef == null ? "" : coverRef;
                return "b64:" + ref.length() + ":" + ref.substring(0, Math.min(32, ref.length()));
            }
            return coverKind + ":" + coverRef;
        }

        byte[] resolveCoverBytes() {
            if (coverRef == null || coverRef.isEmpty()) {
                return null;
            }
            try {
                switch (coverKind) {
                    case URL:
                        return fetchUrlBytes(coverRef);
                    case FILE:
                        return fetchFileBytes(coverRef);
                    case BASE64:
                        return Base64.getDecoder().decode(coverRef);
                    default:
                        return null;
                }
            } catch (Exception ignored) {
                return null;
            }
        }
    }

    private enum CoverKind { NONE, URL, FILE, BASE64 }

    private interface Backend {
        Snapshot poll() throws Exception;
    }

    private static byte[] fetchFileBytes(String pathOrFileUrl) throws IOException, java.net.URISyntaxException {
        File file = pathOrFileUrl.startsWith("file://")
                ? new File(new URI(pathOrFileUrl))
                : new File(pathOrFileUrl);
        try (FileInputStream in = new FileInputStream(file)) {
            return readAllBytes(in);
        }
    }

    private static byte[] fetchUrlBytes(String url) throws IOException {
        URLConnection connection = new URL(url).openConnection();
        connection.setConnectTimeout(3000);
        connection.setReadTimeout(3000);
        try (InputStream in = connection.getInputStream()) {
            return readAllBytes(in);
        }
    }

    private static byte[] readAllBytes(InputStream in) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buffer = new byte[4096];
        int read;
        while ((read = in.read(buffer)) != -1) {
            out.write(buffer, 0, read);
        }
        return out.toByteArray();
    }

    private static String readAllText(InputStream in) throws IOException {
        return new String(readAllBytes(in), StandardCharsets.UTF_8).trim();
    }

    private static String runCommand(String... command) throws IOException, InterruptedException {
        Process process = new ProcessBuilder(command).redirectErrorStream(false).start();
        String output;
        try (InputStream in = process.getInputStream()) {
            output = readAllText(in);
        }
        process.waitFor();
        return output;
    }

    private static long parseLongSafe(String s) {
        try {
            return Long.parseLong(s.trim());
        } catch (NumberFormatException e) {
            return 0L;
        }
    }

    private static double parseDoubleSafe(String s) {
        try {
            return Double.parseDouble(s.trim());
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }

    private static String[] splitFixed(String input, char separator, int count) {
        String[] result = new String[count];
        int start = 0;
        int partIndex = 0;
        for (int i = 0; i < input.length() && partIndex < count - 1; i++) {
            if (input.charAt(i) == separator) {
                result[partIndex++] = input.substring(start, i);
                start = i + 1;
            }
        }
        result[partIndex] = input.substring(start);
        for (int i = partIndex + 1; i < count; i++) {
            result[i] = "";
        }
        return result;
    }

    private static final class LinuxBackend implements Backend {
        private static final char SEP = '\u001F';

        @Override
        public Snapshot poll() throws Exception {
            String format = "{{artist}}" + SEP + "{{title}}" + SEP + "{{mpris:artUrl}}" + SEP + "{{mpris:length}}";
            String metadata = runCommand("playerctl", "metadata", "--format", format);

            if (metadata == null || metadata.isEmpty()) {
                return Snapshot.EMPTY;
            }

            String[] parts = splitFixed(metadata, SEP, 4);
            String artist = parts[0];
            String title = parts[1];
            String artUrl = parts[2];
            long millisLength = parseLongSafe(parts[3]) / 1000L;

            long millisPosition = 0L;
            String positionOutput = runCommand("playerctl", "position");
            if (positionOutput != null && !positionOutput.isEmpty()) {
                millisPosition = (long) (parseDoubleSafe(positionOutput) * 1000.0);
            }

            CoverKind kind = artUrl.startsWith("http://") || artUrl.startsWith("https://")
                    ? CoverKind.URL
                    : CoverKind.FILE;
            return new Snapshot(true, artist, title, millisLength, millisPosition, artUrl, kind);
        }
    }

    private static final class WindowsBackend implements Backend {
        private static final char SEP = '\u001F';
        private File scriptFile;

        @Override
        public Snapshot poll() throws Exception {
            ensureScriptWritten();
            String tempPngPath = File.createTempFile("mpinfo-art-", ".png").getAbsolutePath();

            ProcessBuilder pb = new ProcessBuilder(
                    "powershell", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass",
                    "-File", scriptFile.getAbsolutePath(), tempPngPath);
            pb.redirectErrorStream(false);
            Process process = pb.start();
            String output;
            try (InputStream in = process.getInputStream()) {
                output = readAllText(in);
            }
            process.waitFor();

            if (output == null || output.isEmpty() || output.startsWith("NOMEDIA")) {
                new File(tempPngPath).delete();
                return Snapshot.EMPTY;
            }

            String[] parts = splitFixed(output.trim(), SEP, 5);
            String artist = parts[0];
            String title = parts[1];
            long millisLength = parseLongSafe(parts[2]);
            long millisPosition = parseLongSafe(parts[3]);
            boolean hasArt = "1".equals(parts[4].trim());

            if (hasArt && new File(tempPngPath).length() > 0) {
                return new Snapshot(true, artist, title, millisLength, millisPosition, tempPngPath, CoverKind.FILE);
            } else {
                new File(tempPngPath).delete();
                return new Snapshot(true, artist, title, millisLength, millisPosition, null, CoverKind.NONE);
            }
        }

        private void ensureScriptWritten() throws IOException {
            if (scriptFile != null && scriptFile.exists()) {
                return;
            }
            scriptFile = File.createTempFile("mpinfo-nowplaying-", ".ps1");
            scriptFile.deleteOnExit();
            Files.write(scriptFile.toPath(), POWERSHELL_SCRIPT.getBytes(StandardCharsets.UTF_8));
        }

        private static final String POWERSHELL_SCRIPT =
                "param([string]$ArtPath)\n" +
                        "$SEP = [char]0x1F\n" +
                        "try {\n" +
                        "  Add-Type -AssemblyName System.Runtime.WindowsRuntime | Out-Null\n" +
                        "  $asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | Where-Object {\n" +
                        "    $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and\n" +
                        "    $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1'\n" +
                        "  })[0]\n" +
                        "  function Await($WinRtTask, $ResultType) {\n" +
                        "    $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)\n" +
                        "    $netTask = $asTask.Invoke($null, @($WinRtTask))\n" +
                        "    $netTask.Wait(-1) | Out-Null\n" +
                        "    return $netTask.Result\n" +
                        "  }\n" +
                        "  [Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager,Windows.Media.Control,ContentType=WindowsRuntime] | Out-Null\n" +
                        "  $managerOp = [Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager]::RequestAsync()\n" +
                        "  $manager = Await $managerOp ([Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager])\n" +
                        "  $session = $manager.GetCurrentSession()\n" +
                        "  if ($null -eq $session) { Write-Output 'NOMEDIA'; exit }\n" +
                        "  $propsOp = $session.TryGetMediaPropertiesAsync()\n" +
                        "  $props = Await $propsOp ([Windows.Media.Control.GlobalSystemMediaTransportControlsSessionMediaProperties])\n" +
                        "  $timeline = $session.GetTimelineProperties()\n" +
                        "  $artist = $props.Artist -replace \"`r|`n\", ' '\n" +
                        "  $title = $props.Title -replace \"`r|`n\", ' '\n" +
                        "  $lengthMs = [long]$timeline.EndTime.TotalMilliseconds\n" +
                        "  $posMs = [long]$timeline.Position.TotalMilliseconds\n" +
                        "  $hasArt = 0\n" +
                        "  try {\n" +
                        "    $thumbRef = $props.Thumbnail\n" +
                        "    if ($null -ne $thumbRef) {\n" +
                        "      $streamOp = $thumbRef.OpenReadAsync()\n" +
                        "      $stream = Await $streamOp ([Windows.Storage.Streams.IRandomAccessStreamWithContentType])\n" +
                        "      $netStream = [System.IO.WindowsRuntimeStreamExtensions]::AsStreamForRead($stream)\n" +
                        "      $fileStream = [System.IO.File]::Create($ArtPath)\n" +
                        "      $netStream.CopyTo($fileStream)\n" +
                        "      $fileStream.Close()\n" +
                        "      $hasArt = 1\n" +
                        "    }\n" +
                        "  } catch { $hasArt = 0 }\n" +
                        "  Write-Output ($artist + $SEP + $title + $SEP + $lengthMs + $SEP + $posMs + $SEP + $hasArt)\n" +
                        "} catch {\n" +
                        "  Write-Output 'NOMEDIA'\n" +
                        "}\n";
    }

    private static final class MacBackend implements Backend {
        @Override
        public Snapshot poll() throws Exception {
            String textOut = runCommand("nowplaying-cli", "get", "artist", "title", "duration", "elapsedTime");
            if (textOut == null || textOut.trim().isEmpty()) {
                return Snapshot.EMPTY;
            }

            String[] lines = textOut.split("\\R", -1);
            String artist = lines.length > 0 ? cleanNil(lines[0]) : "";
            String title = lines.length > 1 ? cleanNil(lines[1]) : "";
            long millisLength = lines.length > 2 ? (long) (parseDoubleSafe(cleanNil(lines[2])) * 1000.0) : 0L;
            long millisPosition = lines.length > 3 ? (long) (parseDoubleSafe(cleanNil(lines[3])) * 1000.0) : 0L;

            if (title.isEmpty() && artist.isEmpty()) {
                return Snapshot.EMPTY;
            }

            String artworkBase64 = null;
            try {
                String art = runCommand("nowplaying-cli", "get", "artworkData");
                if (art != null && !art.trim().isEmpty() && !"(null)".equals(art.trim())) {
                    artworkBase64 = art.trim();
                }
            } catch (Exception ignored) {
            }

            CoverKind kind = artworkBase64 != null ? CoverKind.BASE64 : CoverKind.NONE;
            return new Snapshot(true, artist, title, millisLength, millisPosition, artworkBase64, kind);
        }

        private static String cleanNil(String s) {
            if (s == null) {
                return "";
            }
            String trimmed = s.trim();
            return "(null)".equals(trimmed) ? "" : trimmed;
        }
    }
}